import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#131314",
        surface: "#131314",
        "surface-dim": "#131314",
        "surface-bright": "#3a393a",
        "surface-container": "#201f20",
        "surface-container-low": "#1c1b1c",
        "surface-container-high": "#2a2a2b",
        "surface-container-highest": "#353436",
        "surface-container-lowest": "#0e0e0f",
        "surface-variant": "#353436",
        "surface-tint": "#ffffff",
        "on-background": "#e5e2e3",
        "on-surface": "#e5e2e3",
        "on-surface-variant": "#a1a1aa",
        primary: "#ffffff",
        "primary-container": "#d4d4d8",
        "primary-fixed": "#f4f4f5",
        "primary-fixed-dim": "#ffffff",
        "on-primary": "#131314",
        "on-primary-container": "#131314",
        "on-primary-fixed": "#131314",
        "on-primary-fixed-variant": "#27272a",
        "inverse-primary": "#27272a",
        secondary: "#a1a1aa",
        "secondary-container": "#3f3f46",
        "secondary-fixed": "#f4f4f5",
        "secondary-fixed-dim": "#a1a1aa",
        "on-secondary": "#18181b",
        "on-secondary-container": "#d4d4d8",
        "on-secondary-fixed": "#18181b",
        "on-secondary-fixed-variant": "#52525b",
        tertiary: "#a1a1aa",
        "tertiary-container": "#52525b",
        "tertiary-fixed": "#f4f4f5",
        "tertiary-fixed-dim": "#a1a1aa",
        "on-tertiary": "#18181b",
        "on-tertiary-container": "#27272a",
        "on-tertiary-fixed": "#18181b",
        "on-tertiary-fixed-variant": "#71717a",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        outline: "#958ea0",
        "outline-variant": "#494454",
        "inverse-surface": "#e5e2e3",
        "inverse-on-surface": "#313031",
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};
export default config;
