import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const dm_sans = DM_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dm_sans.className} bg-slate-50 w-full flex`}>
        <div className="w-full flex flex-col items-center">
          <Navbar />
          <div className="w-[90%] lg:w-[85%]">{children}</div>
        </div>
      </body>
    </html>
  );
}
